define(['ninejs/css', 'ninejs/config'], function(style, config) {
var result = {path:"client/skin/LoginScreen.css",children:[]};
result.data = "/* Generated using Stylus. DO NOT edit this file directly or your changes may be overwritten */\n.ticketsLoginScreen{width:100%;}.ticketsLoginScreen .login-content h1{color:#fff}.ticketsLoginScreen .c" + 
 "heckIcon.valid{color:#008000}.ticketsLoginScreen .checkIcon.invalid{color:#f00}.ticketsLoginScreen .signInLabel{padding-right:5px}.ticketsLoginScreen .media-object{height:64px;width:64px}.ticketsLogin" + 
 "Screen .input-group{display:table;width:100%}.ticketsLoginScreen .input-group-addon,.ticketsLoginScreen .form-control{display:table-cell}.ticketsLoginScreen .description{color:#fff}"; 
if (config.default.applicationUrl) { result.path = config.default.applicationUrl + result.path; }

return style.style(result);
});